version: 2.1
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.32.1-focal
    steps:
      - checkout
      - run: npm ci
      - run: npm test
      - store_test_results:
          path: test-results
workflows:
  build_and_test:
    jobs:
      - test
